use std::{
    collections::BTreeMap,
    env,
    error::Error,
    fs::File,
    io::{BufWriter, Write},
    path::PathBuf,
};

const MAX_CODEPOINT: u32 = 0x10ffff;
const ELEMENTS_PER_LINE: usize = 3;

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let derived = manifest_dir.join("../DerivedCoreProperties.txt");
    println!("cargo:rerun-if-changed={}", derived.display());
    println!("cargo:rerun-if-changed=build.rs");

    let file = File::open(&derived)?;
    let parsed = unicode_id_trie_rle_derived_core_properties::parse(file)?;

    // Convert the parsed file into a map from codepoint => 2 bit value
    let parsed = parsed
        .iter()
        .filter(|(_, v)| {
            v.contains("ID_Start")
                || v.contains("XID_Start")
                || v.contains("ID_Continue")
                || v.contains("XID_Continue")
        })
        .map(|(k, v)| {
            (
                *k,
                v.iter()
                    .map(|x| {
                        if x.contains("ID_Start") {
                            1 << 0
                        } else if x.contains("ID_Continue") {
                            1 << 1
                        } else {
                            0
                        }
                    })
                    .fold(0, |acc, x| acc | x),
            )
        })
        .collect::<BTreeMap<char, u64>>();

    let mut buffer = Vec::new();
    let mut i = 0;
    while i <= MAX_CODEPOINT {
        let mut value: u64 = 0;
        let mut limit: u32 = 31;
        if i + limit > MAX_CODEPOINT {
            limit = MAX_CODEPOINT - 1;
        }
        for j in 0..=limit {
            let c = match char::from_u32(i + j) {
                Some(x) => x,
                None => continue,
            };
            value |= parsed.get(&c).unwrap_or(&0) << j * 2;
        }
        buffer.push(value);

        i += 32;
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let out_path = out_dir.join("table.rs");
    let out_file = File::create(&out_path)?;
    let mut writer = BufWriter::new(out_file);

    writeln!(writer, "// Code generated by build.rs; DO NOT EDIT.")?;
    writeln!(
        writer,
        "pub(crate) static IDENTIFIER_TABLE: [u64; {}] = [",
        buffer.len()
    )?;

    for idx in 0..buffer.len() {
        if idx % ELEMENTS_PER_LINE == 0 {
            write!(writer, "\t")?;
        }

        write!(writer, "0x{:016x},", buffer[idx])?;

        if idx % ELEMENTS_PER_LINE == ELEMENTS_PER_LINE - 1
            || idx + 1 == buffer.len()
        {
            writeln!(writer)?;
        } else {
            write!(writer, " ")?;
        }
    }

    writeln!(writer, "];")?;
    writer.flush()?;

    Ok(())
}
